# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itell < Formula
  desc "Create and manage itell projects"
  homepage "https://github.com/learlab/itell-cli"
  version "0.0.2"

  on_macos do
    url "https://github.com/learlab/itell-cli/releases/download/v0.0.2/itell-cli_Darwin_all.tar.gz"
    sha256 "9218d57a55a82e39ae1dd87a19766a6091539d86dff748fce575b6918cb93846"

    def install
      bin.install "itell-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/learlab/itell-cli/releases/download/v0.0.2/itell-cli_Linux_x86_64.tar.gz"
        sha256 "f7c345a9eebb2cc0fe210bf1916befd3c8175a8b46d506555373356d3df99c48"

        def install
          bin.install "itell-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/learlab/itell-cli/releases/download/v0.0.2/itell-cli_Linux_arm64.tar.gz"
        sha256 "f96cedd900b16cb1dfe35e477fadf6fd244504da3a4570c8757078c753202695"

        def install
          bin.install "itell-cli"
        end
      end
    end
  end
end
